### ISSUE TITLE
吧50 ——代表完成 50% 改成1~100%区间可不可以？

### ISSUE THREAD

**Issue by xBLACKICEx** [Achuan-2/siyuan-themes-tsundoku-green#1]
吧50 ——代表完成 50% 改成1~100%区间可不可以？

**Comment by Achuan-2** [comment]
可以自己手动加  😅把原来的50%手动copy几个，改成你要的百分数
或者直接在旁边打字，用自定义颜色，也可以啊

**Comment by Achuan-2** [comment]
![image](https://user-images.githubusercontent.com/60436214/133716862-106c1df4-66b2-4e3a-95a3-4afd346f9e8f.png)
你好，已添加10、20、...、100
