### ISSUE TITLE
文件夹图标

### ISSUE THREAD

**Issue by WolkeAtreide** [Achuan-2/siyuan-themes-tsundoku-green#10]
我载入的文件夹不知为何现实错误
![image](https://user-images.githubusercontent.com/101959415/160744713-00d5729d-0cfb-41ed-94e4-aea8f7ea744c.png)

**Comment by Achuan-2** [comment]
![image](https://user-images.githubusercontent.com/60436214/160745029-34556c42-2a7e-43a1-b1bd-051dc392f34b.png)
文件夹请加/
