### ISSUE TITLE
加入langzhou的comment出现了bug

### ISSUE THREAD

**Issue by WolkeAtreide** [Achuan-2/siyuan-themes-tsundoku-green#11]
我将langzhou大佬的comment放进来，结果在点击屏幕上边缘（如图1）的时候遇到了未知bug（如图2）。
https://github.com/langzhou/siyuan-note/tree/main/siyuan-comment
![image](https://user-images.githubusercontent.com/101959415/161056816-c5642c4c-6377-418a-b8c2-f8bdb81d8d58.png)
![image](https://user-images.githubusercontent.com/101959415/161056869-7cc3daf8-e04c-4ca1-bfa0-d15cb1518fe9.png)

**Comment by Achuan-2** [comment]
其他主题有这个问题吗，我没用过这个js

**Comment by WolkeAtreide** [comment]
我试了一下，张亮没这问题
