### ISSUE TITLE
思源最新版本改动了通知消息的显示方式，改动后在主题中不显示或者显示异常

### ISSUE THREAD

**Issue by yixna** [Achuan-2/siyuan-themes-tsundoku-green#12]

**Comment by Achuan-2** [comment]
感谢反馈
https://github.com/Achuan-2/siyuan-themes-tsundoku-green/commit/d37e55fe433d357568a7ab6c4c28139fe2089a63#diff-dff3ae40ade5d29630f230c063582d795566bbc4d4d9bace844e205e65325abbR1167-R1180:~:text=/*%20%E6%B6%88%E6%81%AF%E6%8F%90%E7%A4%BA%20*/,%7D

**Comment by yixna** [comment]
那以后有问题你还会改嘛亲

**Comment by Achuan-2** [comment]
只有在用思源笔记就会更新哦，毕竟我只用自己的主题。
不过以后会很少加主题特有的新特性了，除非自己觉得很必要的
