### ISSUE TITLE
更新一下主题

### ISSUE THREAD

**Issue by yixna** [Achuan-2/siyuan-themes-tsundoku-green#13]
D大动外观了，麻烦不忙了更新一下主题吧，不用你的主题适应不了，辛苦

**Comment by Achuan-2** [comment]
请说明哪些地方不适配哦
已经修复了一些我发现的地方了，等明天主题更新了看看吧

**Comment by yixna** [comment]
感谢感谢，我看着有问题的已经没问题啦，真诚的祝愿你一切顺利！

**Comment by Achuan-2** [comment]
不客气，也祝你一切顺利
