### ISSUE TITLE
绿色主题表格导出，会多出一列的情况，希望能够修复

### ISSUE THREAD

**Issue by KunspireUp** [Achuan-2/siyuan-themes-tsundoku-green#14]
问题参考链接 :https://ld246.com/article/1667653838773?r=Upstream

**Comment by Achuan-2** [comment]
您好，我这边无法复现

**Comment by Upstream-Xiaokun** [comment]
好的，我再看看

**Comment by KunspireUp** [comment]
> 您好，我这边无法复现

好的，我再看看

**Comment by KunspireUp** [comment]
> 您好，我这边无法复现

可以导入sy.zip文件看一下
https://wwf.lanzoue.com/iY2Lu0g33lhg

**Comment by Achuan-2** [comment]
我个人认为这是表格数据由于某些操作被损坏导致的，你可以试试用默认主题导出是不是也是多一列。
你可以试试新建新的表格不会新增一列

**Comment by Achuan-2** [comment]
比如复制这一段到思源，重新导出看看
```markdown
|属性|说明<br />|
| :---------------: | :--------------------------------------------------------------------------------------------|
|series_name|系列名称，用于 tooltip 的显示， legend 的筛选|
|data_pair|系列数据项，格式为[(key1,value1),(key2,value2)]|
|shape|词云图的轮廓，有'circle'、'cardioid'、'diamond'、'trangle-forward'、'pentagon'、'star' 可选|
|word_grap|单词间隔|
|word_size_range|单词字体大小范围|
|roate_step|旋转单词角度|
|tooltip_opts|提示框组件配置项|
```

**Comment by KunspireUp** [comment]
> 比如复制这一段到思源，重新导出看看
> 
> ```gfm
> |属性|说明<br />|
> | :---------------: | :--------------------------------------------------------------------------------------------|
> |series_name|系列名称，用于 tooltip 的显示， legend 的筛选|
> |data_pair|系列数据项，格式为[(key1,value1),(key2,value2)]|
> |shape|词云图的轮廓，有'circle'、'cardioid'、'diamond'、'trangle-forward'、'pentagon'、'star' 可选|
> |word_grap|单词间隔|
> |word_size_range|单词字体大小范围|
> |roate_step|旋转单词角度|
> |tooltip_opts|提示框组件配置项|
> ```

现在可以了，可能就是你说的表格数据操作导致的，以后注意一下

**Comment by Achuan-2** [comment]
好的，那issue关闭了
