### ISSUE TITLE
思源2.5.0版，列表转思维导图显示不正常

### ISSUE THREAD

**Issue by wuyigui323** [Achuan-2/siyuan-themes-tsundoku-green#15]
![image](https://user-images.githubusercontent.com/95500824/202081213-8791b438-031e-43d6-bafc-fbb602703579.png)

**Comment by Achuan-2** [comment]
![image](https://user-images.githubusercontent.com/60436214/202226834-a5e855a0-7983-4250-b3d0-3192e8240e03.png)
i已修复

**Comment by wuyigui323** [comment]
看到有更新，试了已经修复了，感谢您，这个主题颜色非常舒服，我一直用这个模板

**Comment by Achuan-2** [comment]
嘻嘻，谢谢
