### ISSUE TITLE
导出为图片时，无序列表节点显示错误

### ISSUE THREAD

**Issue by tcmtom** [Achuan-2/siyuan-themes-tsundoku-green#16]
![本主题下](https://user-images.githubusercontent.com/94541098/204136716-6574a8d2-470e-439c-9e00-36586854ccee.png)
![软件默认主题下](https://user-images.githubusercontent.com/94541098/204136825-d30c1a02-8362-495e-8fa1-7c02b6d91738.png)

**Comment by Achuan-2** [comment]
已修复
