### ISSUE TITLE
Tsundoku系列主题代码块行号位置偏移

### ISSUE THREAD

**Issue by luommy** [Achuan-2/siyuan-themes-tsundoku-green#17]
Tsundoku
![image](https://user-images.githubusercontent.com/72240631/205419661-2b1435c5-74b9-4cfe-a501-14265c5a65c7.png)

**Comment by luommy** [comment]
如上图所示，其他系列主题和默认主题无此现象，思源笔记v2.5.2 -win10
这个主题用习惯了其他看着都不太舒服，希望作者可以更新下哈哈哈

**Comment by Achuan-2** [comment]
已修复
（平常基本不开行号显示）
