### ISSUE TITLE
搜索界面，左右布局，右侧有一块空白区域

### ISSUE THREAD

**Issue by tcmtom** [Achuan-2/siyuan-themes-tsundoku-green#18]
![image](https://user-images.githubusercontent.com/94541098/206160895-6ac935cb-0e29-48c8-8871-41ee5d691f58.png)
如图所示，默认主题这一块可以显示内容

**Comment by Achuan-2** [comment]
1.4.6版本删除了之前对搜索的自定义样式，应该修复了

**Comment by tcmtom** [comment]
https://github.com/siyuan-note/bazaar/issues/1073#issuecomment-1343834674
好像是没有在theme.json改版本，导致集市没有抓取到更新

**Comment by Achuan-2** [comment]
好的，谢谢。太久不更新主题，都忘记要更新version了

**Comment by tcmtom** [comment]
> 好的，谢谢。太久不更新主题，都忘记要更新version了

更到1.4.7后这个问题解决了
