### ISSUE TITLE
1.41 引用框高度不根据内容

### ISSUE THREAD

**Issue by Kitsuta-le** [Achuan-2/siyuan-themes-tsundoku-green#2]
![image](https://user-images.githubusercontent.com/88605687/136700461-c561c482-9ae2-4c88-9082-84b05c80de57.png)

**Comment by Achuan-2** [comment]
是我故意的啊，会有很大影响吗，对我来说固定高度更舒服

**Comment by Achuan-2** [comment]
https://github.com/Achuan-2/siyuan-themes-tsundoku-green/commit/366ac39ca6b71eb2337dde6c0c72be7b0d4317b2
块引固定高度为70%改为最小高度为30%
