### ISSUE TITLE
2.6.0的闪卡挖空需要适配一下

### ISSUE THREAD

**Issue by tcmtom** [Achuan-2/siyuan-themes-tsundoku-green#20]
https://user-images.githubusercontent.com/94541098/209677814-0db8cbef-dd71-434e-8d60-33e3c243fc66.mp4

就是在闪卡里面不是遮挡的状态

**Comment by Achuan-2** [comment]
我看了下没有问题呀
![image](https://user-images.githubusercontent.com/60436214/212228303-3a3cbde1-411d-4398-a301-84b581f2a482.png)

**Comment by tcmtom** [comment]
> 我看了下没有问题呀 ![image](https://user-images.githubusercontent.com/60436214/212228303-3a3cbde1-411d-4398-a301-84b581f2a482.png)

确实是，我这边也没复现这个问题
