### ISSUE TITLE
块增强菜单里有错别字？

### ISSUE THREAD

**Issue by tcmtom** [Achuan-2/siyuan-themes-tsundoku-green#21]
![image](https://user-images.githubusercontent.com/94541098/209678273-1cfa81e7-a878-4cb1-adb5-7539708d84a2.png)
查看“Markdown”源代码
编辑“Markdown”源代码？

**Comment by Achuan-2** [comment]
都是编辑，ctrl+s可以保存
Markdown就是Markdown
![image](https://user-images.githubusercontent.com/60436214/212228492-eb92373b-5794-45ae-b8ce-8862d32fde67.png)

Kramdown是思源加了块属性的markdown
![image](https://user-images.githubusercontent.com/60436214/212228450-ca7e04f2-bb16-4e52-886e-1d0c2916d69a.png)

**Comment by Achuan-2** [comment]
之后改成这样
![image](https://user-images.githubusercontent.com/60436214/212228684-5c2f101e-cd7c-4a75-9a30-066e611c569b.png)

**Comment by tcmtom** [comment]
> 之后改成这样 ![image](https://user-images.githubusercontent.com/60436214/212228684-5c2f101e-cd7c-4a75-9a30-066e611c569b.png)

那个图标是不是也要修改一下哦😂

**Comment by Achuan-2** [comment]
不改了能用就行

**Comment by tcmtom** [comment]
> 不改了能用就行

好😂
