### ISSUE TITLE
一级标题能否默认居左

### ISSUE THREAD

**Issue by philhappy** [Achuan-2/siyuan-themes-tsundoku-green#4]
最喜欢的思源主题，谢谢大佬
![Uploading 1AF44F01.png…]()

**Comment by Achuan-2** [comment]
你好，谢谢喜欢。
一级标题居中是主题特色，这样有助于直接区分各级标题，集市是不会改的。
如果您需要一级标题默认居左，可以在主题文件夹的theme.css中搜索”标题样式“，删除标注的这段
![image](https://user-images.githubusercontent.com/60436214/139669550-367ca063-19b8-4fa6-9f44-49f645da7002.png)
