### ISSUE TITLE
v1.1.3 代码块行数过小偏移

### ISSUE THREAD

**Issue by MoonBottle** [Achuan-2/siyuan-themes-tsundoku-green#5]
![image](https://user-images.githubusercontent.com/12904505/157846060-813278aa-8ce5-4aa6-930e-ce7f36e534f7.png)
系统 mac 软件版本 1.8.9

**Comment by Achuan-2** [comment]
卸载主题，再安装试试

**Comment by MoonBottle** [comment]
重装之后可以了
