### ISSUE TITLE
一级标题居中可以换一个样式

### ISSUE THREAD

**Issue by winter60** [Achuan-2/siyuan-themes-tsundoku-green#6]
非常喜欢您的主题~
不过对于一级标题居中感觉太违和了，能换一个样式吗？只是一个建议，完全不用顾虑采纳不采纳~

**Comment by Achuan-2** [comment]
那您觉得什么样式好呢，主要我个人很少用一级标题，一般都是导出作为文章标题，或者利用一级标题为中介把部分内容拖动成子文档

**Comment by winter60** [comment]
居左，在原有样式上加粗就很好看~ 看开发者您的习惯就好
确实导出成文章一级居中也很方便，不过作为笔记个人还是偏喜欢markdown 默认样式偏左

**Comment by Achuan-2** [comment]
嗯，可以自行根据需要修改，众口难调吧，分享主题也只是分享一个模板

**Comment by winter60** [comment]
> 嗯，可以自行根据需要修改，众口难调吧，分享主题也只是分享一个模板

好的~
