### ISSUE TITLE
思源程序从1.9.4升级到1.9.5后 PDF背景色出现问题？

### ISSUE THREAD

**Issue by winter60** [Achuan-2/siyuan-themes-tsundoku-green#7]
siyuan-themes-tsundoku-green主题 打开pdf时，背景却是白色的，之前的都是浅绿色。
我试过了，确实是思源升级后的问题，大佬可以分析一下是什么原因吗或者做做兼容？

如果是我的问题，麻烦大佬告知一下，谢谢啦~

![image](https://user-images.githubusercontent.com/23653326/160523180-85054e92-eb76-4cbb-b945-34b9e3f44a46.png)

**Comment by Achuan-2** [comment]
https://github.com/siyuan-note/siyuan/issues/4398
改了pdf库，暂时找不到修改的方法

**Comment by winter60** [comment]
> [siyuan-note/siyuan#4398](https://github.com/siyuan-note/siyuan/issues/4398) 改了pdf库，暂时找不到修改的方法
那去给D大反应一下？我看好像所有的主题都是白色背景或黑色背景了~

**Comment by Achuan-2** [comment]
去吧，如果确实需要的话

**Comment by Vanessa219** [comment]
你说的是红框里面的颜色不对么？
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/970828/160813181-5ef9534f-4649-446b-8be8-bf05cd6f3e3b.png">

**Comment by Achuan-2** [comment]
ta是希望蓝框即pdf文字背景适应主题色
这个灰色是我今天改配色，改漏了……
![image](https://user-images.githubusercontent.com/60436214/160813538-26be7bc6-940e-41ec-bdf4-7b38edaa04e1.png)

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/4439?utm_source=ld246.com

**Comment by Achuan-2** [comment]
1.9.6 已修复
