### ISSUE TITLE
语雀提示框不能生效

### ISSUE THREAD

**Issue by WolkeAtreide** [Achuan-2/siyuan-themes-tsundoku-green#8]
输入':::'+'info'+回车
不能生成提示框

**Comment by Achuan-2** [comment]
您好，只是搬运语雀提示区块的样式，但无法通过语雀的语法来调用的，实际用的还是引述块+背景色来更改样式的
样式介绍见：https://www.yuque.com/achuan-2/siyuan/obxpvr
我能想到比较好的方式是新建四种类别的模板，然后根据模板调用https://www.yuque.com/achuan-2/siyuan/hqvznh
