### ISSUE TITLE
关于无序列表转表格

### ISSUE THREAD

**Issue by WolkeAtreide** [Achuan-2/siyuan-themes-tsundoku-green#9]
f-bg与f-table似乎效果不一样
bg:
![image](https://user-images.githubusercontent.com/101959415/160744253-0641437a-878a-4c7f-bd44-f5d284626847.png)

table:
![image](https://user-images.githubusercontent.com/101959415/160744170-56e9c102-74a6-4a8f-9621-3806a07193de.png)

**Comment by Achuan-2** [comment]
如果可以的话请提供markdown源码，我试下

**Comment by WolkeAtreide** [comment]
可以，不过要如何提供给你？源码指的是markdown文档么？

**Comment by WolkeAtreide** [comment]
github的消息提醒完全没用，还得我自己挨个issue逛。

**Comment by Achuan-2** [comment]
> github的消息提醒完全没用，还得我自己挨个issue逛。

绑定邮箱就会自动发邮件了

**Comment by Achuan-2** [comment]
> 可以，不过要如何提供给你？源码指的是markdown文档么？

直接粘贴无序列表到这里就可以了，反正也没多少字

**Comment by WolkeAtreide** [comment]
* ((20220310222956-oan945a 'Diary'))

  * ((20220311085644-4dih0c4 'January'))

    * ((20220311085522-esn21l0 'February'))

      * ((20220310223023-j700eso 'March'))

        * ((20220311082542-py0jv2i 'April'))
  * ((20220311084331-rvu9imu 'May'))

    * ((20220311084410-86lyc0c 'June'))

      * ((20220311101838-5o93hdu 'July'))

        * ((20220311102158-tdgyg2y 'August'))
  * ((20220311102401-v94lqgl 'September'))

    * ((20220311102533-aflyhih 'October'))

      * ((20220311102707-n8orijx 'November'))

        * ((20220310224415-6c0c601 'November'))
* **Readingnotes**

  * ((20220308190928-4txqg1r 'Literature'))

    * ((20220330133515-ebr98kb 'Economy'))
* **Learn**

  * ((20220220180642-7coodwc 'DA'))

    * ((20220225215231-u1gl95t "SQL"))

      * ((20220226154941-br47rku 'tableau'))

        * ((20220216105756-exuo43t 'Python'))
* **Essay**

  * ((20220312202549-nszk4t5 'Roam'))

    * [2022](assets/DailyNote/2022)

      * [桌面](file://D:\OneDrive\图片\桌面)
* **Knowledge**

  * ((20220326163733-27pxwnb 'Everything'))

    * ((20220329204329-bah1ums 'good words'))
  * ((20220329195039-ztihrw7 'Knowledge'))

    * ((20220313114029-3j7dhhv 'Notes'))
    * ((20220329195157-f79r9l7 'Videos'))

**Comment by WolkeAtreide** [comment]
我这就比较奇怪，之前收到过相关邮件，但是最近收不到了

**Comment by Achuan-2** [comment]
我没有问题哦，你看下主题是否更新了

**Comment by WolkeAtreide** [comment]
你这没问题就行，反正我一般用f-bg

**Comment by Achuan-2** [comment]
好的
